### ISSUE TITLE
Block AI Crawlers on Kedro Website

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-website#198]
## Description:

To prevent unwanted AI crawlers from accessing and scraping content on the Kedro website, we should implement directives to control AI crawlers as per Netlify's guide on blocking AI bots and controlling crawlers - [Netlify Guide on Blocking AI Bots and Controlling Crawlers](https://developers.netlify.com/guides/blocking-ai-bots-and-controlling-crawlers/)

We noticed this on Kedro website, and assume the surge on certain days is due to AI crawlers, 

![image (2)](https://github.com/user-attachments/assets/a82bcf63-dfb8-4366-8a76-ba17990b9015)

**Comment by stichbury** [comment]
Is it a problem? I would have thought we want to be crawled by all and sundry so that we feature in AI-generated search results 🤔

**Comment by astrojuanlu** [comment]
Our documentation yes 👍🏼 our website and blog, not so sure. But it's a good point @stichbury.

The problem is that some AI crawlers happen to be _very_ poorly written (the irony is not lost on me) and it almost costs us money to serve our website last month.

Maybe we should have an allow-list of crawlers.

**Comment by tynandebold** [comment]
>  it almost costs us money to serve our website last month.

For context, we rose just above 50% of our allotted function invocations for the month three days before end of the billing cycle.

![image (9)](https://github.com/user-attachments/assets/da4fb4ea-37e8-4dce-9b73-03e55d388624)

If memory serves, this was only the second or third time this has happened in nearly three years since we launched kedro.org.

Not to say we shouldn't guard against this! Hope we can find a balance between the usefulness of crawlers and not having to pay for their potential inefficiencies.
