### ISSUE TITLE
Find inspiration and create designs for blog.kedro.org

### ISSUE THREAD

**Issue by tynandebold** [kedro-org/kedro-website#62]
## Description

Following on from #61, this ticket deals with with the design implementation of blog.kedro.org.

## Acceptance criteria and deliverables

- Research other tech blogs for reference materials and inspiration.
- Design an initial concept and layout of a blog landing page (the feed) and a blog's post page.

**Comment by comym** [comment]
Hi team, have we defined all the inputs we'll have here?

Something like?

- Post Headline
- Post itself (body)
- Photos
- Videos
- External links
- Author
... 



Also, confirm what basic functionalities we should include.

Something like:

- Search
- Tagging
- Gallery view / feed view 

Thoughts? @tynandebold @Mackay031

**Comment by tynandebold** [comment]
That covers a lot of it. We'll also want code snippets. Can't forget those.

We should get @stichbury's input here as well.

**Comment by stichbury** [comment]
Thanks @tynandebold @comym 

I think we need:

- Post head + post subhead
- H2 - H4 headings
- Usual formatting options for text blocks
- Quote blocks (for callouts -- I'd like to have those too if possible)
- Code snippets
- Side index of H2-H4 headings for navigation
- Author photo & link to author page with byline + existing posts
- Publication date + last updated date (kinda important to have both if possible, otherwise it needs to be clear it's the last update date, or have some kind of history view)
- Video & graphic upload/embed
- Featured graphic (hero graphic)
- Lead graphic (for blog home page, so we can have a list of all recent posts with graphical card, plus have a featured post etc etc)
- SEO Meta title + Meta text
- Twitter card (graphic and text)
- Search
- Categories (and possibly tags)

I'll have the moon on a stick too please if you can manage it :) Happy to discuss any and all of these and prioritise.

I guess I'm aspiring to the kind of blog of where I've just come from (https://ably.com/blog) but happy to work to get that in stages, and some of it can certainly wait!

**Comment by Mackay031** [comment]
Thanks for all the input. I am researching inspiration on this. Will post when I have something solid....

**Comment by tynandebold** [comment]
The designs are here: https://www.figma.com/file/e2FveRnPmCidpGnuyTWbGj/Kedro-Blog-Ideas?node-id=8%3A51336&t=bJ2JaEX9XfC4ejsJ-1
