### ISSUE TITLE
Add Experiment Tracking as a feature on the website

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro-website#65]
## Description

We don't mention Experiment Tracking at all on kedro.org. This would be the design the experiment tracking feature module on kedro.org.

**Comment by comym** [comment]
Hi, 


I've added a new image to be used for the Experiment Tracking module, instead of a screenshot of the whole page.
Let's see if it works.

[Link to the image](https://mckinsey.ent.box.com/file/1065814315387?s=iqzgurmeunqm9wfr8oalaecov7cowd4f)


![Image](https://user-images.githubusercontent.com/55446576/201719269-050490d7-5fcb-49ed-ad35-e3badf8d4612.png)
